--
-- Copyright 2004-2013 The Kuali Foundation
--
-- Licensed under the Educational Community License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.opensource.org/licenses/ecl2.php
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

CREATE TABLE HR_TAX_RATE_T (
HR_TAX_RATE_ID varchar(60) PRIMARY KEY NOT NULL, 
DEPT varchar(21), 
DESCRIPTION varchar(75), 
ORG varchar(10), 
CHART varchar(10), 
LOCATION varchar(20) NOT NULL, 
EFFDT date, 
TIMESTAMP timestamp NOT NULL, 
ACTIVE varchar(1), 
PYRLL_APPRVL varchar(1));


CREATE UNIQUE INDEX HR_TAX_RATE_IDX1 ON HR_TAX_RATE_T
(
  DEPT,
  LOCATION,
  EFFDT,
  TIMESTAMP
);
CREATE INDEX HR_TAX_RATE_IDX3 ON HR_TAX_RATE_T
(
  LOCATION,
  EFFDT,
  TIMESTAMP
)
;
CREATE INDEX HR_TAX_RATE_IDX2 ON HR_TAX_RATE_T
(
  CHART,
  EFFDT,
  TIMESTAMP
)
;


INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,DEPT,DESCRIPTION,ORG,CHART,LOCATION,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('1','CA-DEPT','California Dept',null,null,'CA',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,DEPT,DESCRIPTION,ORG,CHART,LOCATION,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('10','IA-DEPT','Iowa Dept',null,null,'IA',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,DEPT,DESCRIPTION,ORG,CHART,LOCATION,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('11','IA-EC','Earn Code Dept',null,null,'IA',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,DEPT,DESCRIPTION,ORG,CHART,LOCATION,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('12','IA-LEAVE','Iowa Leave Dept',null,null,'IA',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,DEPT,DESCRIPTION,ORG,CHART,LOCATION,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('13','IA-TIME','Iowa Time Dept',null,null,'IA',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,DEPT,DESCRIPTION,ORG,CHART,LOCATION,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('14','IN-CAL','Calendar Dept',null,null,'IN',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,DEPT,DESCRIPTION,ORG,CHART,LOCATION,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('15','IN-DEPT','Indiana Dept',null,null,'IN',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,DEPT,DESCRIPTION,ORG,CHART,LOCATION,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('16','IN-DLUN','Lunch Ded Dept',null,null,'IN',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,DEPT,DESCRIPTION,ORG,CHART,LOCATION,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('17','IN-DOT','Daily OT Dept',null,null,'IN',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,DEPT,DESCRIPTION,ORG,CHART,LOCATION,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('18','IN-EC','Earn Code Dept',null,null,'IN',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,DEPT,DESCRIPTION,ORG,CHART,LOCATION,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('19','IN-LEAVE','Indiana Leave Dept',null,null,'IN',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,DEPT,DESCRIPTION,ORG,CHART,LOCATION,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('2','CA-LEAVE','California Leave Dept',null,null,'CA',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,DEPT,DESCRIPTION,ORG,CHART,LOCATION,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('20','IN-OVT','Weekly OT Dept',null,null,'IN',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,DEPT,DESCRIPTION,ORG,CHART,LOCATION,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('21','IN-SFDF','Shift Diff Dept',null,null,'IN',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,DEPT,DESCRIPTION,ORG,CHART,LOCATION,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('22','IN-TCOLL','Time Collection Dept',null,null,'IN',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,DEPT,DESCRIPTION,ORG,CHART,LOCATION,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('23','IN-TIME','Indiana Time Dept',null,null,'IN',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,DEPT,DESCRIPTION,ORG,CHART,LOCATION,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('3','CA-TIME','California Time Dept',null,null,'CA',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,DEPT,DESCRIPTION,ORG,CHART,LOCATION,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('4','CO-DEPT','Colorado Dept',null,null,'CO',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,DEPT,DESCRIPTION,ORG,CHART,LOCATION,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('5','CO-LEAVE','Colorado Leave Dept',null,null,'CO',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,DEPT,DESCRIPTION,ORG,CHART,LOCATION,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('6','CO-TIME','Colorado Time Dept',null,null,'CO',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,DEPT,DESCRIPTION,ORG,CHART,LOCATION,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('7','GA-DEPT','Georgia Dept',null,null,'GA',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,DEPT,DESCRIPTION,ORG,CHART,LOCATION,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('8','GA-LEAVE','Georgia Leave Dept',null,null,'GA',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,DEPT,DESCRIPTION,ORG,CHART,LOCATION,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('9','GA-TIME','Georgia Time Dept',null,null,'GA',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
