--
-- Copyright 2004-2013 The Kuali Foundation
--
-- Licensed under the Educational Community License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.opensource.org/licenses/ecl2.php
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

DROP TABLE HR_TAX_RATE_T;
CREATE TABLE HR_TAX_RATE_T (
HR_TAX_RATE_ID varchar(60) PRIMARY KEY NOT NULL, 
COUNTRY varchar(2),  NOT NULL, 
STATE varchar(2) NOT NULL, 
CITY varchar(4) NOT NULL, 
ORG varchar(10), 
CHART varchar(10), 
EFFDT date, 
TIMESTAMP timestamp NOT NULL, 
ACTIVE varchar(1), 
PYRLL_APPRVL varchar(1));


CREATE UNIQUE INDEX HR_TAX_RATE_IDX1 ON HR_TAX_RATE_T
(
  COUNTRY,
  STATE,
  CITY,
  EFFDT,
  TIMESTAMP
);
CREATE INDEX HR_TAX_RATE_IDX3 ON HR_TAX_RATE_T
(
  STATE,
  EFFDT,
  TIMESTAMP
)
;
CREATE INDEX HR_TAX_RATE_IDX2 ON HR_TAX_RATE_T
(
  CHART,
  EFFDT,
  TIMESTAMP
)
;


INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,COUNTRY,CITY,ORG,CHART,STATE,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('1','US','',null,null,'CA',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,COUNTRY,CITY,ORG,CHART,STATE,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('10','US','',null,null,'IA',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,COUNTRY,CITY,ORG,CHART,STATE,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('11','US','',null,null,'IA',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,COUNTRY,CITY,ORG,CHART,STATE,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('12','US','',null,null,'IA',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,COUNTRY,CITY,ORG,CHART,STATE,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('13','US','',null,null,'IA',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,COUNTRY,CITY,ORG,CHART,STATE,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('14','US','',null,null,'IN',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,COUNTRY,CITY,ORG,CHART,STATE,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('15','US','',null,null,'IN',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,COUNTRY,CITY,ORG,CHART,STATE,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('16','US','',null,null,'IN',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,COUNTRY,CITY,ORG,CHART,STATE,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('17','US','',null,null,'IN',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,COUNTRY,CITY,ORG,CHART,STATE,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('18','US','',null,null,'IN',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,COUNTRY,CITY,ORG,CHART,STATE,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('19','US','',null,null,'IN',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,COUNTRY,CITY,ORG,CHART,STATE,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('2','US','',null,null,'CA',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,COUNTRY,CITY,ORG,CHART,STATE,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('20','US','',null,null,'IN',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,COUNTRY,CITY,ORG,CHART,STATE,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('21','US','',null,null,'IN',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,COUNTRY,CITY,ORG,CHART,STATE,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('22','US','',null,null,'IN',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,COUNTRY,CITY,ORG,CHART,STATE,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('23','US','',null,null,'IN',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,COUNTRY,CITY,ORG,CHART,STATE,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('3','US','',null,null,'CA',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,COUNTRY,CITY,ORG,CHART,STATE,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('4','US','',null,null,'CO',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,COUNTRY,CITY,ORG,CHART,STATE,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('5','US','',null,null,'CO',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,COUNTRY,CITY,ORG,CHART,STATE,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('6','US','',null,null,'CO',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,COUNTRY,CITY,ORG,CHART,STATE,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('7','US','',null,null,'GA',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,COUNTRY,CITY,ORG,CHART,STATE,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('8','US','',null,null,'GA',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
INSERT INTO HR_TAX_RATE_T (HR_TAX_RATE_ID,COUNTRY,CITY,ORG,CHART,STATE,EFFDT,TIMESTAMP,ACTIVE,PYRLL_APPRVL) VALUES ('9','US','',null,null,'GA',{d '2010-01-01'},{ts '1970-01-01 00:00:00.'},'Y',null);
